spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enable: false
    gateway:      routes:      - id: employee-service
        uri: lb://EMPLOYEE-API
        predicates:        - Path=/employee/**           
server:  port: 8080